# Generated by Django 5.0.6 on 2024-08-06 21:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fast', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prueba',
            name='id',
        ),
        migrations.AddField(
            model_name='prueba',
            name='si',
            field=models.CharField(default=django.utils.timezone.now, max_length=501, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
